# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-06 16:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('horario', models.CharField(choices=[('LyM', (('1', "Lunes y Miercoles 'Matutino'"), ('2', "Lunes y Miercoles 'Vespertino'"))), ('MyJ', (('1', "Martes y Jueves 'Matutino'"), ('2', "Martes y Jueves 'Vespertino'"))), ('VyS', (('1', "Viernes y Sabado 'Matutino'"), ('2', "Viernes y Sabado 'Vespertino'")))], max_length=50)),
                ('comienza', models.TimeField(default='00:00')),
                ('termina', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Membrecia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('domicilio', models.CharField(max_length=60)),
                ('fecha_de_nacimimiento', models.DateField()),
                ('mebrecia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Membrecia')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicacion_fecha', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_de_vencimiento', models.DateTimeField(default=datetime.datetime(2017, 1, 6, 16, 23, 30, 476000, tzinfo=utc))),
                ('Realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Miembro')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Membrecia')),
            ],
            options={
                'ordering': ['fecha_de_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('ciudad', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'ordering': ['salon'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('plaza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='gym.Sucursal')),
                ('servicio_de_maquinas', models.BooleanField()),
                ('servicio_de_nutricion', models.BooleanField()),
                ('servicio_de_clase', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Salones',
                'ordering': ['plaza'],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='miembros',
            field=models.ManyToManyField(to='gym.Miembro'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Salon'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Salon'),
        ),
        migrations.AddField(
            model_name='membrecia',
            name='aplica_en',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Salon'),
        ),
        migrations.AddField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Salon'),
        ),
    ]
